### ISSUE TITLE
Adapt to Docker metadata/labeling changes from upstream

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-task-app-starters/app-starters-release#61]
This is required for SCDF 2.5 and onwards.

- [x] Update Task Core: https://github.com/spring-cloud-task-app-starters/core/issues/17
- [x] Update Composed Task Runner https://github.com/spring-cloud-task-app-starters/composed-task-runner/issues/113
- [x] Update Timestamp Batch Task https://github.com/spring-cloud-task-app-starters/timestamp-batch/issues/18
- [x] Update Timestamp Task https://github.com/spring-cloud-task-app-starters/timestamp/issues/18

**Comment by tzolov** [comment]
Nothing left to do
